# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://localhost:8080/FsBlog
gitlocation: https://github.com/jeremyabbott/jeremyabbott.github.io.git
gitbranch: master
title: Jeremy Abbott 
description: >
    I need a description

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes
